### ISSUE TITLE
Remove doubled title 

### ISSUE THREAD

**Issue by ElminaIusifova** [sara-sabr/auto-evaluation-devops-self-assessment#39]
<img width="1010" alt="Screen Shot 2021-03-24 at 2 29 34 PM" src="https://user-images.githubusercontent.com/32398063/112366258-f9518700-8cae-11eb-86da-0f613b2dd5b6.png">
1. remove doubled  DevOps Sel-Assessment   title
2. revome home
3. increase title font size

**Comment by smellems** [comment]
Removed extra app name and made title bigger.

Home is still there..  Realated to #41
