### ISSUE TITLE
All questions mandatory

### ISSUE THREAD

**Issue by smellems** [sara-sabr/auto-evaluation-devops-self-assessment#48]
All question are marked as mandatory in the JSON and on the the Website with * but there is no warning or error when leaving questions blank.  It counts as 0.

**Comment by gcharest** [comment]
Need to look at overall behavior desired. Marked as mandatory was when we required all questions to be so.  Introducing a back and forth user navigation and a by page display required to bypass the mandatory flags. Logic to be reviewed.

**Comment by gcharest** [comment]
Suggested behaviour: can't see results unless all questions in section are answered. This way submit fully answered section only.

**Comment by gcharest** [comment]
Incorporate in #50
