### ISSUE TITLE
Error 404 when reloading 

### ISSUE THREAD

**Issue by ElminaIusifova** [sara-sabr/auto-evaluation-devops-self-assessment#59]
Very often this error appears when the user reloads the page or navigates back to the application from our website

<img width="1092" alt="Screen Shot 2021-04-26 at 3 27 26 PM" src="https://user-images.githubusercontent.com/32398063/116139373-f37f0500-a6a3-11eb-88ef-3af475ddef90.png">

**Comment by gcharest** [comment]
I've noticed this happens when someone visits a page other than home directly. Will look into the router options setup.

**Comment by smellems** [comment]
https://router.vuejs.org/guide/essentials/history-mode.html

**Comment by gcharest** [comment]
Need to use https://router.vuejs.org/guide/essentials/history-mode.html#native-node-js or https://github.com/bripkens/connect-history-api-fallback

**Comment by gcharest** [comment]
From second link: 

> Single Page Applications (SPA) typically only utilise one index file that is accessible by web browsers: usually index.html. Navigation in the application is then commonly handled using JavaScript with the help of the HTML5 History API. This results in issues when the user hits the refresh button or is directly accessing a page other than the landing page, e.g. /help or /help/online as the web server bypasses the index file to locate the file at this location. As your application is a SPA, the web server will fail trying to retrieve the file and return a 404 - Not Found message to the user.

**Comment by gcharest** [comment]
Tested as much as I can but need some step by step to reproduce error if fix doesn't fully works.

Thanks!
