### ISSUE TITLE
Add an error message once some questions are not answered

### ISSUE THREAD

**Issue by ElminaIusifova** [sara-sabr/auto-evaluation-devops-self-assessment#66]
For now, if some questions in the tool are not answered it still gives the score. We might want to add an error message if some questions are missed by a user

**Comment by gcharest** [comment]
Are all questions mandatory? Asking as we had removed that behavior to let the user come and go as they see fit.

I can add the mandatory back plus prevent user from leaving the section before completing all the questions. Some development required around:
- If there's still an error on the current section, then no results are saved locally.

The reason why is that the user can always click on the home or return button which means they bypass any controls we implement in the Questions page.
